config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'join#index'
  root 'join#index'
  resources :subscribers, only: [:create, :index]
  resources :users, only: [:index]
  resources :app, only: %i(index)

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  namespace :api do 
    namespace :v1 do
      resources :games, only: %i(index create update) do
        resources :duplicate, controller: 'games/duplicate'
      end
      resources :markets_with_ev, only: %i(index)
      resources :simulation, only: %i(index)
      resources :uncollected_games, only: %i(index)
      resources :upcoming_games, only: %i(index)
      resources :teams, only: %i(index)
      resources :leagues, only: %i(index)
      resources :switch_sides, only: %i(update)
    end
  end

  authenticated do
    get 'admin', to: 'admin#index'

    get 'admin/odds_scraper', to: 'admin/odds_scraper#index'

    resources :games do
      resources :duplicate, only: [:create], controller: 'games/duplicate'
      put 'switch_side', controller: 'games/switch_side'
    end

    resources :contracts
    resources :players
    resources :articles
    resources :splits
    resources :leagues, only: %i(destroy create new index edit show)

    resources :teams do
      resources :games, only: [:index], controller: 'teams/games'
    end
  end

  namespace :api do
    namespace :v1 do
      delete 'session', to: 'session#destroy'
      resources :data, only: [:index]
      resources :bank_accounts, only: [:index]
      resources :settings, only: %i(index)
      resources :bets
      resources :unsettled_bets, only: %(index)
      resources :upcoming_games, only: [:index]
      resources :odds, only: %i(create show)
      resources :scrapers, only: %i(create index)
      resources :splits, only: %i(show index) do
        resources :stats, only: %i(index), controller: 'splits/stats'
      end

      resources :teams, only: [:show, :index] do
        resources :first_markets, only: [:index, :show], controller: 'teams/first_markets'
      end
      resources :games, only: %i(show)

      resources :leagues do
        resources :splits, only: %i(index), controller: 'leagues/splits'
      end
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  FIRST_MARKETS = %w(blood turret dragon baron).freeze
  FIRST_MARKETS_SHORT = %w(fb ft fd fbaron win).freeze
  enum first_turret_type: [ :top, :middle, :bottom ]

  belongs_to :league
  belongs_to :split
  has_many :bets, dependent: :destroy

  validates :game_number, presence: true, numericality: { greater_than_or_equal_to: 1 }

  scope :complete, -> { where.not(winner_id: nil, loser_id: nil) }

  def self.upcoming_game_with_teams(t1, t2)
    one = where(blue_side_team_id: t1.id, red_side_team_id: t2.id, winner_id: nil)
    another = where(blue_side_team_id: t2.id, red_side_team_id: t1.id, winner_id: nil)

    if one.count > 0
      return one.first
    elsif another.count > 0
      return another.first
    else
      throw "Did not find game for #{t1.name} vs #{t2.name}"
    end
  end

  # given a game a team, get the other (not given) team
  def opposing_team(first_team)
    if blue_side_team_id == first_team.id
      return red_side_team
    end

    blue_side_team
  end

  def date_only
    date.to_s.split(' ').first
  end

  def odds_for_team_in_market(team_id, market)
    team_side = red_side_team_id == team_id ? 'red_side' : 'blue_side'

    self["#{team_side}_team_#{market}_odds"]
  end

  def winner 
    Team.find winner_id
  end

  def teams
    Team.where(id: [red_side_team_id, blue_side_team_id])
  end

  def loser
    Team.find loser_id
  end

  def red_side_team
    Team.find red_side_team_id
  end

  def blue_side_team
    Team.find blue_side_team_id
  end

  def first_team_to_get(market)
    id = self["first_#{market}_team_id"]
    Team.find id if id
  end

  def player_to_get_first(market)
    id = self["first_#{market}_player_id"]
    Player.find id if id
  end

  def complete?
    !winner_id.nil? && !loser_id.nil?
  end
end

app/controllers/api/v1/games/duplicate_controller.rb
module Api
  module V1
    module Games
      class DuplicateController < ActionController::API
        def create
          game = Game.find params[:game_id]
          dup_game = game.dup
          dup_game.update_attributes!(
            game_number: dup_game.game_number + 1,
            first_blood_team_id: nil,
            first_turret_team_id: nil,
            first_dragon_team_id: nil,
            first_baron_team_id: nil,
            winner_id: nil,
            loser_id: nil
          )

          render json: dup_game
        end
      end
    end
  end
end

app/controllers/api/v1/games_controller.rb
module Api
  module V1
    class GamesController < ActionController::API
      def index
        period_start = params[:start] 
        period_end = params[:end] 
        
        if period_start and period_end
          games = Game.all
            .where('date > ?', period_start)
            .where('date < ?', period_end)
            .to_json(methods: [:teams])

          render json: games
        else
          render json: Game.all
        end
      end

      def create
        render json: Game.create!(game_params)
      end

      def update
        game = Game.find(params[:id])
        game.update_attributes!(game_params)

        # Settle bets if game is complete
        SettleBetsService.new(game).call if game.complete?

        render json: Game.find(params[:id])
      end

      def show
        render json: Game.find(params[:id]).to_json(methods: [:teams])
      end

      private

      def game_params
        params.require(:game).permit(
          :id,
          :first_blood_team_id,
          :first_turret_team_id,
          :first_dragon_team_id,
          :first_baron_team_id,
          :winner_id,
          :loser_id,
          :red_side_team_id,
          :blue_side_team_id,
          :game_number,
          :date,
          :league_id,
          :split_id,

          :blue_side_team_fb_odds, :blue_side_team_ft_odds, 
          :blue_side_team_fd_odds, :blue_side_team_fbaron_odds, 

          :red_side_team_fb_odds, :red_side_team_ft_odds, 
          :red_side_team_fd_odds, :red_side_team_fbaron_odds, 
        )
      end
    end
  end
end

app/controllers/api/v1/teams/games_controller.rb
module Api
  module V1
    module Teams
      class GamesController < ::ActionController::API
        def index
          render json: { 'ok': 'ok' }
        end
      end
    end
  end
end

app/controllers/games/duplicate_controller.rb
module Games
  class DuplicateController < ApplicationController
    def create
      game = Game.find(params[:game_id]).dup
      game.game_number = game.game_number += 1

      game.save!

      redirect_to game
    end
  end
end

app/controllers/games/switch_side_controller.rb
module Games
  class SwitchSideController < ApplicationController
    def switch_side
      @game = Game.find(params[:game_id])
      authorize @game
      switched_game = SwitchSidesService.new(@game).call

      redirect_to edit_game_url(@game)
    end

    private

    def switch_side_params
      params.require(:game_id)
    end
  end
end

app/controllers/games_controller.rb
require 'securerandom'

class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all.order(date: :asc)
  end

  def destroy
    authorize @game
    @game.delete

    redirect_to games_path
  end

  def new
    @game = Game.new
    authorize @game
    @game.game_number = 1
    @teams = Team.all.order(name: :asc)
    @league = League.last
    # TODO: don't hard code this?
    @splits = @league.splits
  end

  def show
    authorize @game
    set_first_teams
  end

  def create
    game = Game.new(game_params)
    authorize game
    game.match_uuid = SecureRandom.uuid if game.game_number == 1
    game.save!

    redirect_to edit_game_url(game)
  end

  def edit
    authorize @game
    set_players_for_first
    @teams = FormHelper.select_for(@game.teams)
    @players_for_select = @game.teams.first.players.collect {|t| [ t.name, t.id ] }
  end

  def update
    authorize @game
    @game.update_attributes!(game_params)
    SettleBetsService.new(@game).call if @game.complete?

    redirect_to @game
  end

  private

  # Get the correct list of players based on which team 
  # got the first blood/dragon
  def set_players_for_first
    Game::FIRST_MARKETS.each do |market|
      team_id =  @game["first_#{market}_team_id".to_sym]

      if team_id
        set_players_instance_variable(market, Team.find(team_id).players)
      else 
        set_players_instance_variable(market, @game.teams.first.players)
      end
    end
  end

  def set_players_instance_variable(market, players)
    instance_variable_set(
      "@players_for_first_#{market}", players.collect {|p| [ p.name, p.id ] } 
    )
  end

  # Set the first team for each market dynamically 
  def set_first_teams
    Game::FIRST_MARKETS.each do |market|
      if @game["first_#{market}_team_id".to_sym]
        instance_variable_set(
          "@first_#{market}_team", @game.send("first_team_to_get", market).name)
      end
    end
  end

  def game_params
    params.require(:game).permit(
      :game_number, :match_uuid,

      :blue_side_team_id, :red_side_team_id, :date,
      :blue_side_team_win_odds, :red_side_team_win_odds,

      :blue_side_team_fb_odds, :blue_side_team_ft_odds, 
      :blue_side_team_fd_odds, :blue_side_team_fbaron_odds, 

      :red_side_team_fb_odds, :red_side_team_ft_odds, 
      :red_side_team_fd_odds, :red_side_team_fbaron_odds, 

      :first_blood_team_id, :first_turret_team_id,
      :first_baron_team_id, :first_dragon_team_id,

      :first_turret_type, 
      :first_blood_player_id, :first_turret_player_id,
      :first_baron_player_id, :first_dragon_player_id,

      :winner_id, :loser_id,

      :league_id, :split_id,

      :match_complete
    )
  end

  def set_game
    @game = Game.find(params[:id])
  end
end

app/controllers/teams/games_controller.rb
module Teams
  class GamesController < ApplicationController
    def index
      @team = Team.find(params[:team_id])
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
  def self.opposing_team(game, home_team)
    game.teams.where.not(id: home_team.id).first
  end
end

app/views/games/_form.html.erb
<div class="btns">
  <%= form_with url: game_switch_side_path(@game), method: :put do |form| %>
    <%= form.submit 'Switch Sides', id: 'switch_sides' %>
  <% end %>

  <%= form_with url: game_path(@game), method: :delete do |f| %>
    <%= f.submit 'Delete', data: { confirm: 'Are you sure?' }%>
  <% end %>
</div>

<%= form_with model: @game do |f| %>
  <div class="first_market">
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div class="odds match_uuid">
    <%= f.label :match_uuid %>
    <%= f.text_field :match_uuid %>
  </div>

  <div class="odds">
    <%= f.label :game_number %>
    <%= f.number_field :game_number %>
  </div>

  <div class="odds">
    <div class="first_market">
      <%= f.label :blue_side %>
      <%= f.select :blue_side_team_id, @teams, { }, { class: 'side_select' } %>
    </div>

    <div class="odds">
      <%= f.label :odds, for: 'game_blue_side_team_win_odds', class: 'odds_label' %>
      <%= f.text_field :blue_side_team_win_odds %>
    </div>
  </div>

  <div class="odds">
    <div class="first_market">
      <%= f.label :red_side %>
      <%= f.select :red_side_team_id, @teams, {}, { class: 'side_select' } %>
    </div>

    <div class="odds">
      <%= f.label :odds, for: 'game_red_side_team_win_odds', class: 'odds_label' %>
      <%= f.text_field :red_side_team_win_odds %>
    </div>
  </div>

  <h3>First Blood</h3>
  <div class="first_market">
    <%= f.label :first_blood_team_id %>
    <%= f.select :first_blood_team_id, @teams, { include_blank: '----' }, { class: 'first_select', data_select: 'first_blood' } %>
  </div>

  <div class="odds">
    <%= f.label :blue_side_team_fb_odds %>
    <%= f.text_field :blue_side_team_fb_odds %>
  </div>

  <div class="odds">
    <%= f.label :red_side_team_fb_odds %>
    <%= f.text_field :red_side_team_fb_odds %>
  </div>


  <h3>First Turret</h3>
  <div class="first_market">
    <%= f.label :first_turret_team_id %>
    <%= f.select :first_turret_team_id, @teams, { include_blank: '----' }, { class: 'first_select', data_select: 'first_turret' } %>
  </div>

  <div class="odds">
    <%= f.label :blue_side_team_ft_odds %>
    <%= f.text_field :blue_side_team_ft_odds %>
  </div>

  <div class="odds">
    <%= f.label :red_side_team_ft_odds %>
    <%= f.text_field :red_side_team_ft_odds %>
  </div>

  <div class="first_market">
    <%= f.label :first_turret_type %>
    <%= f.select(:first_turret_type, Game.first_turret_types.collect { |t| [ t[0], t[0] ] }) %>
  </div>

  <h3>First Dragon</h3>
  <div class="first_market">
    <%= f.label :first_dragon_team_id %>
    <%= f.select :first_dragon_team_id, @teams, { include_blank: '----' }, { class: 'first_select', data_select: 'first_dragon' } %>
  </div>

  <div class="odds">
    <%= f.label :blue_side_team_fd_odds %>
    <%= f.text_field :blue_side_team_fd_odds %>
  </div>

  <div class="odds">
    <%= f.label :red_side_team_fd_odds %>
    <%= f.text_field :red_side_team_fd_odds %>
  </div>

  <h3>First Baron</h3>
  <div class="first_market">
    <%= f.label :first_baron_team_id %>
    <%= f.select :first_baron_team_id, @teams, { include_blank: '----' }, { class: 'first_select', data_select: 'first_baron' } %>
  </div>

  <div class="odds">
    <%= f.label :blue_side_team_fbaron_odds %>
    <%= f.text_field :blue_side_team_fbaron_odds %>
  </div>

  <div class="odds">
    <%= f.label :red_side_team_fbaron_odds %>
    <%= f.text_field :red_side_team_fbaron_odds %>
  </div>

  <h3>Result</h3>

  <div class="first_market">
    <%= f.label :winner_id %>
    <%= f.select :winner_id, @teams, { include_blank: '----' } %>
  </div>

  <div class="first_market">
    <%= f.label :loser_id %>
    <%= f.select :loser_id, @teams, { include_blank: '----' } %>
  </div>

  <div class="first_market">
    <%= f.label :match_complete %>
    <%= f.check_box :match_complete %>
  </div>

  <%= f.submit %>
<% end %>

app/views/games/_new_form.html.erb
<%= javascript_pack_tag 'games/new' %>

<%= form_with model: @game do |f| %>
  <div class="first_market">
    <%= f.label :date %>
    <%= f.date_field :date, value: Date.today %>
  </div>

  <div class="first_market">
    <%= f.label :league %>
    <%= f.select :league_id, FormHelper.select_for(League.all), { selected: @league.id }, { class: 'side_select', data_select: 'league_select' } %>
  </div>

  <div class="first_market">
    <%= f.label :split %>
    <%= f.select :split_id, FormHelper.select_for(@splits.all), { selected: @splits.last.id }, { class: 'side_select', data_select: 'split_select' } %>
  </div>

  <div class="first_market">
    <%= f.label :blue_side %>
    <%= f.select :blue_side_team_id, FormHelper.select_for(@teams), { selected: @teams.first.id }, { class: 'side_select' } %>
  </div>

  <div class="first_market">
    <%= f.label :red_side %>
    <%= f.select :red_side_team_id, FormHelper.select_for(@teams), { selected: @teams.second.id }, { class: 'side_select' } %>
  </div>

  <div class="first_market">
    <%= f.label :game_no %>
    <%= f.number_field :game_number, id: 'game_game_no' %>
  </div>

  <%= f.submit %>
<% end %>

app/views/games/edit.html.erb
<%= javascript_pack_tag "games/edit" %>

<h2>
  <%= @game.blue_side_team.name %> vs <%= @game.red_side_team.name %> (Game <%= @game.game_number %>)
</h2>

<div class="game_edit">
  <%= render partial: 'form' %>
</div>

app/views/games/index.html.erb
<h3>All Games</h3>

<div>
  <%= link_to 'New Game', new_game_url %>
</div>

<% @games.each do |game| %>

  <div data-test-game>
    <%= game.date.strftime("%Y/%m/%d") %> <%= game.blue_side_team.name %> vs <%= game.red_side_team.name %>
    <%= link_to 'Edit', edit_game_path(game), method: :get %>
  </div>

<% end %>

app/views/games/new.html.erb
<div class="game_new">
  <%= render partial: 'new_form' %>
</div>

app/views/games/show.html.erb
<div class="game_show">

  <%= link_to 'Back to App', app_index_path %>
  <div>
    <%= @game.date.strftime("%Y/%m/%d") %>
  </div>

  <% if @game.winner_id && @game.loser_id %>

    <span class="winner"><%= @game.winner.name %></span> vs <%= @game.loser.name %>

  <% else %>

    <%= @game.blue_side_team.name %> vs <%= @game.red_side_team.name %>

  <% end %>

  (<%= @game.match_uuid %>)
</div>

<br>

<div>
  Red Side: <%= @game.red_side_team.name %> (<%= @game.red_side_team_win_odds %>)
</div>

<div>
  Blue Side: <%= @game.blue_side_team.name %> (<%= @game.blue_side_team_win_odds %>)
</div>

<br>

<div>
  First blood (<%= gametime(@game.first_blood_time) %>): 
  <%= @game.first_team_to_get('blood').try(:name) %> 
  (<%= @game.player_to_get_first('blood').try(:name) %>)
  Blue odds: <%= @game.blue_side_team_fb_odds %> Red odds: <%= @game.red_side_team_fb_odds %>
</div>

<div>
  First turret (<%= gametime(@game.first_turret_time) %>): 
  <%= @game.first_team_to_get('turret').try(:name) %> 
  (<%= @game.player_to_get_first('turret').try :name %>)
  Blue odds: <%= @game.blue_side_team_ft_odds %> Red odds: <%= @game.red_side_team_ft_odds %>
</div>

<div>
  First dragon (<%= gametime(@game.first_dragon_time) %>): 
  <%= @game.first_team_to_get('dragon').try(:name) %> 
  (<%= @game.player_to_get_first('dragon').try :name %>)
  Blue odds: <%= @game.blue_side_team_fd_odds %> Red odds: <%= @game.red_side_team_fd_odds %>
</div>

<div>
  First baron (<%= gametime(@game.first_baron_time) %>): <%= @game.first_team_to_get('baron').try(:name) %> (<%= @game.player_to_get_first('baron').try :name %>)
  Blue odds: <%= @game.blue_side_team_fbaron_odds %> Red odds: <%= @game.red_side_team_fbaron_odds %>
</div>

<%= link_to 'Edit', edit_game_path(@game), method: :get %>

<%= button_to 'Duplicate', game_duplicate_index_path(@game), method: :post %>