config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'join#index'
  root 'join#index'
  resources :subscribers, only: [:create, :index]
  resources :users, only: [:index]
  resources :app, only: %i(index)

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  namespace :api do 
    namespace :v1 do
      resources :games, only: %i(index create update) do
        resources :duplicate, controller: 'games/duplicate'
      end
      resources :markets_with_ev, only: %i(index)
      resources :simulation, only: %i(index)
      resources :uncollected_games, only: %i(index)
      resources :upcoming_games, only: %i(index)
      resources :teams, only: %i(index)
      resources :leagues, only: %i(index)
      resources :switch_sides, only: %i(update)
    end
  end

  authenticated do
    get 'admin', to: 'admin#index'

    get 'admin/odds_scraper', to: 'admin/odds_scraper#index'

    resources :games do
      resources :duplicate, only: [:create], controller: 'games/duplicate'
      put 'switch_side', controller: 'games/switch_side'
    end

    resources :contracts
    resources :players
    resources :articles
    resources :splits
    resources :leagues, only: %i(destroy create new index edit show)

    resources :teams do
      resources :games, only: [:index], controller: 'teams/games'
    end
  end

  namespace :api do
    namespace :v1 do
      delete 'session', to: 'session#destroy'
      resources :data, only: [:index]
      resources :bank_accounts, only: [:index]
      resources :settings, only: %i(index)
      resources :bets
      resources :unsettled_bets, only: %(index)
      resources :upcoming_games, only: [:index]
      resources :odds, only: %i(create show)
      resources :scrapers, only: %i(create index)
      resources :splits, only: %i(show index) do
        resources :stats, only: %i(index), controller: 'splits/stats'
      end

      resources :teams, only: [:show, :index] do
        resources :first_markets, only: [:index, :show], controller: 'teams/first_markets'
      end
      resources :games, only: %i(show)

      resources :leagues do
        resources :splits, only: %i(index), controller: 'leagues/splits'
      end
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :contracts
  has_many :teams, through: :contracts
  belongs_to :position

  def current_team
    contracts.order(start: :desc).first.team unless contracts.count == 0
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
    @teams = teams
    @positions = positions
  end

  def create
    @player = Player.create!(player_params)
    redirect_to edit_player_url(@player)
  end

  def show
    @player = Player.find(params[:id])
  end

  def index
    @players = Player.all.order(name: :asc)
  end

  def update
    @player = Player.find(params[:id])
    @player.update_attributes!(player_params)
    redirect_to @player
  end

  def edit
    @player = Player.find(params[:id])
    @teams = teams
    @positions = positions
    @new_contract = Contract.new(player: @player)
    @teams = teams
  end

  private

  def player_params 
    params.require(:player).permit(
      :name,
      :position_id,
      :team_id
    )
  end

  def teams
    Team.all.collect {|t| [ t.name, t.id ] }
  end

  def positions
    Position.all.collect {|t| [ t.name, t.id ] }
  end
end

app/views/players/_form.html.erb
<%= form_with model: @player do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :position %>
  <%= f.select :position_id, @positions %>

  <%= f.submit %>
<% end %>

app/views/players/edit.html.erb
<%= render partial: 'form' %>

<% @player.contracts.each do |contract| %>
  <hr>
  Contract with <%= contract.team.name %>

  <%= form_with model: contract do |f| %>
    <%= f.label :start %>
    <%= f.date_field :start %>

    <%= f.label :end_date %>
    <%= f.date_field :end_date %>

    <%= f.submit %>
  <% end %>
<hr>

<% end %>

<h3>New Contract</h3>

<%= form_with model: @new_contract do |f| %>
  <%= f.hidden_field :player_id %>
  <%= f.label :start %>
  <%= f.date_field :start %>

  <%= f.label :end_date %>
  <%= f.date_field :end_date %>

  <%= f.label :team_id %>
  <%= f.select :team_id, @teams %> 

  <%= f.submit %>
<% end %>

app/views/players/index.html.erb
<h3>Players</h3>

<% @players.each do |player| %>
  <div>
    <b><%= player.name %></b>
    <div>
      Position: <%= player.position.name %>
    </div>
    <div>
      Team: <%= player.current_team ? player.current_team.name : 'unsigned'  %>
    </div>

    <%= link_to 'edit', edit_player_path(player) %>  
  </div>
  <br>
<% end %>

app/views/players/show.html.erb
<h3><%= @player.name %></h3>

<div>Position: <%= @player.position.name %></div>
<div>Team: <%= @player.current_team ? @player.current_team.name : 'Unsigned'  %></div>