config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'join#index'
  root 'join#index'
  resources :subscribers, only: [:create, :index]
  resources :users, only: [:index]
  resources :app, only: %i(index)

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  namespace :api do 
    namespace :v1 do
      resources :games, only: %i(index create update) do
        resources :duplicate, controller: 'games/duplicate'
      end
      resources :markets_with_ev, only: %i(index)
      resources :simulation, only: %i(index)
      resources :uncollected_games, only: %i(index)
      resources :upcoming_games, only: %i(index)
      resources :teams, only: %i(index)
      resources :leagues, only: %i(index)
      resources :switch_sides, only: %i(update)
    end
  end

  authenticated do
    get 'admin', to: 'admin#index'

    get 'admin/odds_scraper', to: 'admin/odds_scraper#index'

    resources :games do
      resources :duplicate, only: [:create], controller: 'games/duplicate'
      put 'switch_side', controller: 'games/switch_side'
    end

    resources :contracts
    resources :players
    resources :articles
    resources :splits
    resources :leagues, only: %i(destroy create new index edit show)

    resources :teams do
      resources :games, only: [:index], controller: 'teams/games'
    end
  end

  namespace :api do
    namespace :v1 do
      delete 'session', to: 'session#destroy'
      resources :data, only: [:index]
      resources :bank_accounts, only: [:index]
      resources :settings, only: %i(index)
      resources :bets
      resources :unsettled_bets, only: %(index)
      resources :upcoming_games, only: [:index]
      resources :odds, only: %i(create show)
      resources :scrapers, only: %i(create index)
      resources :splits, only: %i(show index) do
        resources :stats, only: %i(index), controller: 'splits/stats'
      end

      resources :teams, only: [:show, :index] do
        resources :first_markets, only: [:index, :show], controller: 'teams/first_markets'
      end
      resources :games, only: %i(show)

      resources :leagues do
        resources :splits, only: %i(index), controller: 'leagues/splits'
      end
    end
  end
end

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'Teams', teams_path %>
  <%= link_to 'Players', players_path %>
  <%= link_to 'Games', games_path %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125733430-1"></script>
    <% if Rails.env == 'production' %>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-125733430-1');
      </script>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      const qs = x => document.querySelector(x)
      const qss = x => document.querySelectorAll(x)
    </script>
  </head>
  
  <%#= render partial: 'layouts/header' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/join.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tag %>

<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125733430-1"></script>
<script>
<% if Rails.env == 'production' %>
    window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-125733430-1', {
  'page_title' : 'landing_page',
  'page_path': '/'
});
<% end %>
</script>


<style>

.color-1 { color: pink }
.color-2 { color: hotpink; }
.color-3 { color: gold; }
.color-4 { color: lightblue; }
.color-5 { color: peachpuff; }
</style>

<div class="outer">
  <div class="bg wrapper">
    <div class="hero-text">
      <p>
      Let <span class="color-2">data</span> 
      drive your betting.</span> 
      </p>
      <p>
      Hi, I'm Lachlan, a <span class="color-2">data scientist</span> and <span class="color-3">League of Legends</span> fan. 
      I'm building an <span class="color-2">analytics platform</span> to optimize my 
      <span class="color-1">LCS betting</span>.
      </p>

      <p>
      I've had <span class="color-3">great results</span> during the <span class="color-1">NA LCS 2019 Summer Split</span>. I've fined tuned my platform and have opened it to <span class="color-2">public.</span>
      You should probably be familiar with some basic concepts, such as the 
      <span class="color-2"><a href="/expected_value.html">expected value (EV)</a></span>, the basic idea
      LCS tracking, and most <span class="color-2">statistical betting systems</span> are build on.
      </p>

      <p>
      <a href="/app" class="color-1">Click here to try it out.</a>
      </p>

    </div>

    <%= image_tag 'app_preview.png', { class: 'app_preview img_1' } %>

  </div>

</div>

<style>
html, body { 
  background-color: black; 
  padding: 0px; 
  margin: 0px; 
  border: 0px;
}

@media screen and (max-width: 480px) {
}

.outer { 
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: black;
  width: 100vw;
}

.wrapper {
  max-width: 800px;
  padding-top: 100px;
}

@media screen and (max-width: 480px) {
  .wrapper {
    flex-direction: column;
    padding-top: 0px;
    margin: 10px;
  }
}


.hero-text, form {
  width: 100%;
}

form {
  margin: 0 20px;
}

@media screen and (max-width: 480px) {
  form {
    margin: 15px 0 15px 0;
  }
}

.join-btn, .join-field {
  width: 100%;
  height: 50px;
  margin: 8px 0;
}

.join-field > input {
  color: black;
  padding: 8px;
}

.join-btn > input, .join-field > input {
  font-size: 1rem;
  width: 100%;
  height: 100%;
}

input[type='submit'] {
  background-color: orange;
  -webkit-appearance: none;
  border: none;
}

a {
  text-decoration: underline;
}

.hero-text, input {
  line-height: 1.5;
  color: white;
  font-family: 'Comfortaa', cursive;
}

.loading {
  opacity: 0.5;
}

.app_preview {
  border: 3px solid grey;
}

.img_1 {
  width: 100%;
  object-fit: scale-down;
}

a {
  color: gold;
}
</style>